version: '3'

services:
  dashboard:
    restart: unless-stopped
    build: .
    env_file:
      - ./prod.env
    ports:
      - '80:3000'
    volumes:
      - /app/node_modules
      - .:/app
    tty: true
